# -*- coding: utf-8 -*-
"""SUMMARY_REPORT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZmg5e1EIMjaOWQk3Q2Eo-oCafQnzL3A
"""

# Commented out IPython magic to ensure Python compatibility.
# Move into the team repository directory
# %cd ML_project_team-404_not-found

# Define the summary report text
markdown_content = """# Team 404 Not Found - Master Dataset Summary Report

## Overview
This repository contains a compiled, standardized dataset of Python bug instances, stack traces, and ground-truth patches mined from three different sources.

## Dataset Breakdown

| Data Source | Member Responsible | Target Sample Count | Key Features / Notes |
| :--- | :--- | :--- | :--- |
| **SWE-bench Lite / BugsInPy** | Member 1 | 30–50 | Validated historical patches, pytest failure commands, clear stack traces. |
| **Live GitHub CI Logs** | Member 2 | 15–20 | Extracted raw CI logs, mapped tree-sitter AST nodes for failing lines. |
| **Synthetic Bug Injection** | Member 3 (You) | 15–20 | Mutated edge cases (off-by-one errors, missing None checks, altered return values). |
| **Total Master Dataset** | **Team 404 Not Found** | **60–90** | **Unified into `master_dataset.json`** |

## Master JSON Schema Structure
All collected samples are structured using the following schema:
- `id`: Unique identifier for the bug entry
- `source`: Origin of data (`swe_bench`, `ci_logs`, or `synthetic_mutation`)
- `repo_name`: Name of the target Python repository
- `commit_sha`: Git commit hash before the fix
- `failing_test_command`: Terminal command used to trigger the error
- `raw_error_log`: Complete pytest output / traceback
- `ground_truth_patch`: Human patch / unified diff to resolve the bug
- `ast_scope`: Function or class AST node extracted via Tree-sitter
"""

# Write the file directly to the folder
with open("SUMMARY_REPORT.md", "w") as f:
    f.write(markdown_content)

print("SUMMARY_REPORT.md has been generated successfully!")